### ISSUE TITLE
Handle differences in capitalisation

### ISSUE THREAD

**Issue by jean** [hackebrot/labels#15]
If `labels.toml` has `blocked`, and `Blocked` already exists:

```
DEBUG labels sync: Creating label 'blocked' for owner/repo
Error creating label blocked: 422 - Unprocessable Entity
```

One approach: compare lowercased labels, and silently update to whatever is in `labels.toml`. E.g. in this case `Blocked`->`blocked`. 

Another approach: fail, saying that there is a case mismatch.

**Comment by hackebrot** [comment]
Hi @jean! 👋 

Please post the TOML contents for the current state and the desired state. What does the GitHub API documentation suggest? Is it expected to return a 422 for this? Or does it expect a PATCH request and fails for a POST request because of that? 🤔

**Comment by hackebrot** [comment]
Ping @jean! 🙂

**Comment by hackebrot** [comment]
Closing this as inactive. Happy to re-open later. 📝
