### ISSUE TITLE
Add -f, --file FILENAME option

### ISSUE THREAD

**Issue by felker** [hackebrot/labels#2]
First off, thanks for making this tool! I have been looking all day for what I assumed would be a common/straightforward task of exporting and importing GitHub Labels between repositories. Most of the older tools have not been updated since the [February 2018 Label improvements](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/) and do not transfer Label Descriptions. And the use of TOML is a huge improvement over XML, JSON, and YAML implementations, in my opinion.

I wonder if the project could benefit from allowing the `labels.toml` default filename to be overridden using a `-f FILENAME` or `--file FILENAME` flag syntax. This would allow a user to have a repository that would sync the GitHub labels from many projects, e.g. `repo1.toml`, `repo2.toml`, ....

Other ideas that came across my mind are:

- [ ] Update `README.md` to describe the `-u` and `-t` flags
- [ ] Add `write` command that would not delete target repository labels as `sync` might do, but adds/replaces conflicts with only the contents of `labels.toml`. Would not change/update contents of `labels.toml` (assuming section names match their `names` parameters).

I see your `CONTRIBUTING.md` is under construction, but I would be happy to submit a PR for some/all of these feature requests.

**Comment by hackebrot** [comment]
Hi @felker! 👋 

Thank you for your feedback! Is is much appreciated 🙇

I added some info to our ``CONTRIBUTING.md`` in 1ec22bde03256e79eb2a39d5300d1945787e63cf. It's rather minimal at this point, but covers the most important ways in which one can contribute to this project.

The reason I didn't include ``-u`` and ``-t`` in our README is because, in my experience, it's easier for newcomers to get started with using a project if there is only one way to do a certain task. In this particular case, I decided to focus on environment variables. We could add a note to the CLI usage section though.

The CLI flags ``-f, --filename`` are already supported, see [README](https://github.com/hackebrot/labels#fetch).

Can you give a use case for the ``write`` command? If a user doesn't want to delete any labels, they would leave any of these labels unchanged in the labels TOML file.

Thanks again for your feedback and suggestions! 📝

**Comment by felker** [comment]
I now see that `-f, --filename` are documented in the README. I missed it because I think it is absent from the `@click.option()` calls in `cli.py` and thus doesn't show up in the `--help` output.

I think it might be worth a brief mention of `-t`, `-u` in the README to prompt users to check out `labels --help` for more info on how to use them. For example, simply adding:
> Alternatively, these values can be specified via the command line interface.

at the end of the Authentication section.

The `write` command would be useful for how I am using the tool. A project I work on is hosted on a private GitHub repository, say `project_dev`, and there is a public version of the code in another GitHub repository `project_public`. The latter simply receives periodic updates from the private development repository and accepts bug report and feature request Issues from the public users.

It would be useful to periodically export the labels from `project_dev` to a file `dev_labels.toml` and completely overwrite the issue labels on `project_public` so that they mirror the private repository, even if labels were deleted at some point. Obviously, this can be achieved from `sync` with workarounds, but I thought I would suggest a useful case.

**Comment by hackebrot** [comment]
I added the flag to both the [fetch][fetch] and the [sync][sync] commands, which means it shows up for the help messages for each respective command:

```text
$ labels fetch --help
```
```text
Usage: labels fetch [OPTIONS]

  Fetch labels for a GitHub repository.

  This will write the labels information to disk to the specified filename.

Options:
  -o, --owner TEXT     GitHub owner name  [required]
  -r, --repo TEXT      GitHub repository name  [required]
  -f, --filename PATH  Filename for labels  [required]
  --help               Show this message and exit.
```

[pull request]: https://github.com/hackebrot/labels/compare

[sync]: https://github.com/hackebrot/labels/blob/master/src/labels/cli.py#L85
[fetch]: https://github.com/hackebrot/labels/blob/master/src/labels/cli.py#L55

**Comment by hackebrot** [comment]
Do you want to submit a [pull request][pull request], so that your username appears in the GitHub contributors for that change?

[pull request]: https://github.com/hackebrot/labels/compare

**Comment by hackebrot** [comment]
You can export the labels from ``project_dev`` to a file ``dev_labels.toml`` via

```text
$ labels fetch -o felker -r project_dev -f dev_labels.toml
```

And completely overwrite the issue labels on ``project_public`` via

```text
$ labels sync -o felker -r project_public -f dev_labels.toml
```

Can you please try this out and let me know if that works for you?

**Comment by felker** [comment]
I see the `-f, --file` option documentation in the `fetch` and `sync` commands now; forgive my ignorance of the Click package. I am only used to `argparse` behavior and output, so I only looked for the output of `labels --help`. And if a user tries `labels fetch --help` with the requisite environment variables undefined:
```
K-MBP% labels fetch --help
Usage: labels [OPTIONS] COMMAND [ARGS]...

Error: Missing option "-u" / "--username".
```
Adding the `-u, -t` flags or environment variables obviously reproduces the correct help message above, although `-f` isn't truly a "required" option, correct?

I'd be happy to submit a PR for any changes--- which one in particular did you have in mind?

**Comment by felker** [comment]
I just tried your steps, with an added deletion of a label between the `fetch` and `sync` commands, and it worked as expected. I guess I misinterpreted the `sync` command--- it behaves exactly as I had intended `write` to behave! Sorry for the noise.
